version: '3.1'

volumes:
  db-card:

services:
  card_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER={CARD_DB_USER}
      - POSTGRES_PASSWORD={CARD_DB_PASSWORD}
      - POSTGRES_DB={CARD_DB-NAME}
    volumes:
      - db-card:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    image: card_service
    restart: always
    build: .
    depends_on:
      card_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://card_db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"